TOP = 20
TO_FIND = """MTMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSS
WRVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLELLDKYLIPNATQPESKVFY
LKMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFY
YEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGD
AGEGEN"""
PART = 7
ALPHABET = {'M', 'R', 'B', 'U', 'Q', 'W', 'G', 'P', 'L', 'D', 'E', 'T', 'Z', 'N', 'X', 'F',
            'Y', 'V', 'A', 'I', 'S', 'H', 'K', 'O', 'C'}
DATA_PATHS = "data/data-big.txt"